remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
google_site_verification: 1fA8S_WIStPRX_f9yDGy-0aM-9tDwdCl6om0N1J5aSU
show_excerpts: false
show_downloads: true
github:
  is_user_page: false
  is_project_page: false
timezone: Europe/Moscow
